import { OnboardingDraft } from './types'

export function createDefaultDraft(): OnboardingDraft {
  return {
    preferredName: '',
    destinationCountry: '',
    destinationCity: '',
    destinationUniversity: '',
    destinationUnknownCountry: false,
    destinationUnknownCity: false,
    destinationUnknownUniversity: false,
    nationality: '',
    residenceCountry: '',
    isEuCitizen: 'unknown',
    degreeType: '',
    fieldOfStudy: '',
    fieldOfStudyUnknown: false,
    programStartMonth: '',
    programStartMonthUnknown: false,
    programApplied: '',
    programAccepted: '',
    hasGmatOrEntranceTest: '',
    gmatScore: '',
    hasEnglishTest: '',
    englishTestType: '',
    englishTestScore: '',
    hasRecommendationLetters: '',
    hasCv: '',
    admissionStatus: '',
    deadlinesKnown: 'unknown',
    passportExpiry: '',
    visaType: '',
    visaAppointmentNeeded: 'unknown',
    hasVisa: '',
    hasCodiceFiscale: '',
    hasResidencePermit: '',
    hasHousing: '',
    needsBankAccount: '',
    hasBankAccount: '',
    needsPhoneNumber: '',
    hasPhoneNumber: '',
    hasTravelInsurance: '',
    hasHealthInsurance: '',
    monthlyBudgetRange: 'unknown',
    scholarshipNeed: 'maybe',
    fundingSource: 'unknown',
    housingPreference: 'unknown',
    moveInWindow: '',
    housingSupportNeeded: 'unknown',
    lastCompletedStep: 0,
    checklistItems: {},
    updatedAt: undefined,
  }
}
